language: java
before_install:
- cd libs && ./install.sh && cd ..
after_success:
- ./createLibrary.sh
deploy:
  provider: releases
  api_key:
    secure: TdQ/JwwC93aW30NRuMEo21UB1s0l94O1yNJ5n8KXgE3s2Ket7M31khoVfbJf3s7X/cYhy0/9e3Mleek5c1FAX7TlhKG+Zx3lrS7gnYOQbZLwMdewhtqk3rDbOfDXEEnxYy5GvKfwon8pjqg/htQusH5IzNeO+KC7sQ8c1UGBiWg=
  file: OpenvibeLink.tgz
  skip_cleanup: true
